### PR TITLE
Setup deploys to maven central

### LINKED ISSUE #29: migrate to maven central
jcenter will be sunset on May 1, 2020 [announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

### PR DESCRIPTION
**Pull request by eygraber**
Fixes #29 

This is waiting on a few changes from https://github.com/vanniktech/gradle-maven-publish-plugin before it can be used.

@Faltenreich on your end you would need to set up a maven central / sonatype account, and then create the following secrets on this repo:

`secrets.SONATYPE_NEXUS_USERNAME` that has the value of your sonatype username

`secrets.SONATYPE_NEXUS_PASSWORD` that has the value of your sonatype password

`secrets.ARTIFACT_SIGNING_PRIVATE_KEY` that has the value of your signing key

You can update the GitHub action to run tests, etc...

### CODE REVIEW

**Comment by Faltenreich** [comment]
@eygraber Thank you very much for your help! I have registered at Sonatype and filed a new issue at their JIRA: https://issues.sonatype.org/browse/OSSRH-68367. Now I am waiting for the command to verify my domain in order to generate a GPG key pair.

Source: https://proandroiddev.com/publishing-a-maven-artifact-3-3-step-by-step-instructions-to-mavencentral-publishing-bd661081645d

**Comment by eygraber** [comment]
Awesome!

I think once you have added the TXT record, you're supposed to leave a comment on the issue saying something along the lines of "I did that" and then they'll verify it.

**Comment by eygraber** [comment]
@Faltenreich any update on this?

**Comment by Faltenreich** [comment]
I am currently very busy with work but planning to complete this task the next days. Until then please stay tuned, be aware of my thanks and continue to use the artifact from JCenter which is working until February 1st 2022.

**Pull request merged**
